rss_groups:
  技术: &tech
    V2EX创意分享: https://www.v2ex.com/feed/create.xml
    B站野生技能分区: https://rsshub.uneasy.win/bilibili/partion/122
  

chat_ids:
  877702922:
    <<: *tech
    <<: *blog
    <<: *new
    <<: *other

chat_ids:
  -1001436520490:
    <<: *tech
    <<: *blog
    <<: *new
    <<: *other
 
 
