rss_groups:
技术: &tech
    V2EX创意分享:
      url: https://www.v2ex.com/feed/create.xml
      fold: true

  博客: &blog
    
    
  新闻: &new
    
  综合: &other
    B站野生技能分区: https://rsshub.uneasy.win/bilibili/partion/122
  
    
chat_ids:
  -1001436520490:
    <<: *tech
    <<: *blog
    <<: *new
    <<: *other
 
 
