rss_groups:
  分享: &tech
    V2EX创意分享: https://www.v2ex.com/feed/create.xml
    B站野生技能分区: https://rsshub.uneasy.win/bilibili/partion/122
  博客: &blog
    月光博客:
      url: 
      fold: true
    阮一峰的网络日志: 
  efficiency: &new
    efficiencyfollow: https://www.efficiency.vip/atom/discussions
    竹白: https://rsshub.app/zhubai/noise
    公众号: https://rsshub.app/wechat/mp/msgalbum/MzUzODgyNDc5Ng==/2300793028376412163
  综合: &other
    少数派: 

chat_ids:
  -1001436520490:
    <<: *tech
    <<: *blog
    <<: *new
    <<: *other
 
