name: TGRSS_Action

on:               
  schedule:                           
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  rss:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
    - name: Set up Python 3.9.15
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.15
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Process RSS
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        HTTP_PROXY: ''
        HTTPS_PROXY: ''
        SSL_VERIFY: 'true'
      run: python main.py
    - name: Commit
      run: |
        git config --global user.email action@example.org
        git config --global user.name Action
        git add database.json
        git commit -m "update the database" -a
      continue-on-error: true
    - name: Push changes
      uses: ad-m/github-push-action@master 
      with:
        branch: master
        github_token: ${{ secrets.PERSONAL_TOKEN }}
